### ISSUE TITLE
Dutch words containing `ij` are wrongly considered misspelled

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/nspell#13]
In Dutch, the combination `ij` is very common. Every word containing this combination, is considered misspelled.

From looking into the Dutch `aff` I noticed that the unicode character `ĳ` is used for this. I have never seen this character before.

I notifed that something is going on [here](https://github.com/wooorm/dictionaries/blob/master/dictionaries/nl/index.aff#L81-L88), however I am not familiar with the hunspell format.

The following code snippet should log `true`:

```js
const nspell = require('nspell');
const dictionary = require('dictionary-nl');

dictionary((err, dict) => {
  const spell = nspell(dict);
  console.log(spell.correct('wij'));
});
```

**Comment by wooorm** [comment]
@remcohaszing Hello fellow Dutch person!

I believe the opentaal is rather nerdy so they thought they’d use the unicode character (maybe more correct, but a bit pedantic).
In hunspell, those iconv and oconv flags define input replace and output replace, and [they should be handled correctly here](https://github.com/wooorm/nspell/blob/571688f5bef10e2105ddb4a72aa63dd0238f9166/lib/util/affix.js#L132-L142)

**Comment by remcohaszing** [comment]
Thanks for the quick fix! :netherlands:
