### ISSUE TITLE
Typescript Rewrite

### ISSUE THREAD

**Issue by RyanKadri** [wooorm/nspell#23]
First of all, thanks for all the great work you've been doing on nspell. This is a great library. 

I'm a big believer in adding Typescript definitions to libraries as a way to boost usage and improve new developer experience. Unfortunately, I think having separate type definitions comes with some maintainability problems and additional setup friction.

Is there any interest in this project for somebody to help migrate over to Typescript? Seems like it could be a reasonably straightforward process with some nice benefits if you're open to it.

**Comment by wooorm** [comment]
Hi there @RyanKadri! Thanks for offering, but no, I’m not interested in types ([related](https://github.com/search?o=desc&q=user%3Awooorm+typescript&s=updated&type=Issues)). I’m not a fan of TS.
