### ISSUE TITLE
Undoing addition and removal of words

### ISSUE THREAD

**Issue by fabiospampinato** [wooorm/nspell#29]
Words can be added and removed from a dictionary, but I don't see any APIs for reversing those actions 🤔 

My use case is essentially doing the following: Add words -> remove those added words -> add new words.

The "remove those added words" there is not clear how to do it. Like some of those added words might have been already in the dictionary, calling `remove` for them would remove them from the dictionary while I only want to remove them from the list of added words.

I suppose I could instantiate new instances of `nspell` and then just add the updated words to those, but presumably instantiating nspell instances is not a cheap operation 🤔 

I think potentially adding a `reset` method to nspell instances would be a good enough solution to this, assuming that that implements the reset functionality much more efficiently than just reloading the dictionary and affix files.

**Comment by wooorm** [comment]
There was a similar issue recently, where I explained that [hunspell isn’t really made for that](https://github.com/wooorm/nspell/issues/24#issuecomment-652950733), and hence that it doesn’t exist. Adding stuff has effects on the dictionary, but it’s not tracked what those changes are.

Presumably, `reset` would indeed be cheaper than a new instance, but, I’m not sure how `reset` could be implemented 😅

**Comment by fabiospampinato** [comment]
I see 🤔 I guess I'll have to rebuild `nspell` instances then.

Free free to close this if you don't think a more optimized way of doing that will be implemented in the future.

**Comment by fabiospampinato** [comment]
`remove` seems like it could be reversed easily by storing a reference to the removed object and offering a way to put it back into place, perhaps by returning a function that does that. There may be edge cases where that doesn't work, like if the word in the meantime got added slightly differently by some other means, but overall it should work well enough.

`add` seems more difficult to reverse, unless each call to that leads to exactly one word being added to the internal data structure, but I'm not sure about that.

**Comment by wooorm** [comment]
I don’t feel confident in adding functionality that is so error-prone. Could this be done on top instead? E.g., you can access [.data](https://github.com/wooorm/nspell/blob/c92902162193084027a5a8b7259702af90804528/lib/remove.js#L9) and save the info?

**Comment by fabiospampinato** [comment]
Yeah it should be possible to build it on top of he current set of APIs, at least for `remove`.

Anyway the complexity associated with implementing this is not worth it for me. If the APIs were available and reliable already I'd use them, otherwise I'm not going to try to implement this myself. 

If you don't think this will be implemented in nspell itself perhaps we can close this issue.

**Comment by wooorm** [comment]
I’d prefer to stay close to hunspell and be small rather than implementing time-travelling!
