### ISSUE TITLE
"hasSuggestions" API

### ISSUE THREAD

**Issue by fabiospampinato** [wooorm/nspell#30]
I'd like to implement a "loose" spell checking mode, where if a word is not correct but there are no suggestions for it then the spell checker doesn't yell at the user.

I can currently do something like this to check if there are any suggestions:

```ts
const hasSuggestions = !!instance.suggest ( word ).length;
```

But that would compute all possible suggestions, and I don't really care about having them available to me at that point in time, so I'd like nspell to have a method that allows me to implement that in a much more efficient way, like:

```ts
const hasSuggestions = instance.hasSuggestions ( word );
```

Which more practically would exit early from unnecessary expensive loops like this one:

https://github.com/wooorm/nspell/blob/c92902162193084027a5a8b7259702af90804528/lib/suggest.js#L274-L276

**Comment by wooorm** [comment]
Can you expand on why this feature is useful? I.e., real world.
I’m not clear on why [.spell](https://github.com/wooorm/nspell#nspellspellword) is not enough in this case?

**Comment by wooorm** [comment]
(n.b., I understand you’re explicitly asking for `!isCorrect && suggestions.length === 0` compared to `!isCorrect`, but I’m wondering why)

**Comment by fabiospampinato** [comment]
> Can you expand on why this feature is useful? I.e., real world.

I think some people (like me probably) would want the spell checker to shut up if it has no suggestions, or maybe even better I would want incorrect words with no suggestions to be underlined in the editor more subtly (grey rather than red or something like that).

> I’m not clear on why .spell or (.correct) is not enough in this case?

Those alone don't allow me to distinguish between incorrect words with and without suggestions.

**Comment by fabiospampinato** [comment]
Maybe a "maxSuggestions" argument for the `suggest` method instead would be a cleaner way to address this, plus also maybe if there are 100 possible suggestions only the top 5 or something will be used in practice anyway, so breaking out of the loop earlier would be useful in that scenario too.

**Comment by wooorm** [comment]
Ahh. I understand.

There is no way to know whether there are 0 suggestions, except for attempting to find those suggestions, by generating lots of potential words.

There is no way of knowing, if there are 5 valid words, whether those are the good ones (I believe whether a suggestion is good also has to do with how often it is generated).

A short word (say three letters) is very fast to check. A long word can take an immense amount of time to generate.

I don’t really see how to implement an hasSuggestions api other that well, running suggest and checking if there are 0 results.

**Comment by fabiospampinato** [comment]
> I don’t really see how to implement an hasSuggestions api other that well, running suggest and checking if there are 0 results.

That's ok, I'm just proposing adding a way to stop after at the first suggestion is found rather than finding them all which would be useless in some cases.

**Comment by wooorm** [comment]
Does your recent work change your need for this feature? It doesn’t make a lot of sense to me (as the 1st result might be bad)

**Comment by fabiospampinato** [comment]
> Does your recent work change your need for this feature? It doesn’t make a lot of sense to me (as the 1st result might be bad)

Not really. But I've changed my mind on this a bit, the added confusion of having words highlighted differently depending on if they'll have any suggestions or not might not be worth it, like I've never seen a two-tier spell checker like that 🤔 Plus performance-wise this may backfire even, as suggestions can be memoized, but if you need to know if there are any suggestions before actually computing any of them, and then later on computing them, you'll be computing the first suggestion twice rather than once essentially.

So let me close this, eventually if I'll change my mind on this again I'll submit a PR or something.
