### ISSUE TITLE
Pre-parsed dictionaries

### ISSUE THREAD

**Issue by fabiospampinato** [wooorm/nspell#31]
Sometimes parsing a dictionary is a major bottleneck as that can take multiple seconds:

![image](https://user-images.githubusercontent.com/1812093/93717051-26d83f00-fb6b-11ea-8789-dd0abf7d0b25.png)

If it takes that long in the best case scenario the app's spell checking, or whatever feature built on top of nspell, is going to feel broken, in the worst case scenario (single-core machines or machines where all other cores are busy) the app may become pretty unresponsive and slow for long enough that the user will just kill it.

I think a potential way to address this problem would be pre-parsing dictionaries, essentially skipping building the internal data structures from the raw dictionary file and loading them directly. 

Would that be possible? If so could you give me some pointers on how I should go about implementing that? I'm thinking perhaps a `serialize` and `deserialize` methods could be implemented for this purpose.

**Comment by fabiospampinato** [comment]
Also related to this it looks like almost every `add` call puts some significant pressure on the garbage collector, addressing that looks like will be a significant additional win.

**Comment by fabiospampinato** [comment]
I've taken a closer look at the code, would it be correct to think that serialization is a matter of saving and restoring these objects?:

https://github.com/wooorm/nspell/blob/c92902162193084027a5a8b7259702af90804528/lib/index.js#L52-L58

Regarding memory usage there seem to be a good number of unnecessary allocations (creating arrays that are sometimes useless, generating a match object for a regex when it's not actually used etc.) and some arrays get concatenated, throwing away both of the original ones, rather than merged together, throwing away only one of them, I'll start experiment by optimizing those things, let's see how much difference that will make.

**Comment by fabiospampinato** [comment]
> Regarding memory usage there seem to be a good number of unnecessary allocations

Just addressing some of those cut the initialization time almost in half for `dictionary-fr`. Let's see if there's something else that can be optimized.

**Comment by fabiospampinato** [comment]
Regarding serialization serializing the parsed `dictionary-fr` made it 50x bigger, and non JSON-serializable data probably got lost 🤔 gzipping it makes it ~7x bigger, that's still a lot of stuff to download on terrible connections, but on the other hand I guess it would be much less likely that the process will run out of memory parsing that, which I'm not sure how often would happen.

**Comment by fabiospampinato** [comment]
Interestingly the zipped parsed `dictionary-fr` is only ~2x bigger than the zipped raw one, I guess French words can be modified in way more ways than English words.

**Comment by wooorm** [comment]
Thanks for looking into optimizing perf!

Have you looked into putting the spelling on another thread? Spelling is such a slow task, that putting it into a worker might make the most sense?

**Comment by fabiospampinato** [comment]
@wooorm Yeah I'm already running nspell in a web worker, otherwise everything would just hang. I was actually thinking about using multiple web workers, I'm not sure if this feasible because I'm not too sure about how the whole thing works, but do you think for example chunking the dictionary in 4 parts, making a nspell instance for each of them, and then managing them all would essentially parallelize the entire thing? Or would that not work for some reason?

**Comment by wooorm** [comment]
Hmm, I don’t really see that working. May depend on the dictionary, but a bunch of languages have super complex compounding where several “words” make up one single “word”

**Comment by fabiospampinato** [comment]
Right, there are languages like german that may be problematic in that regard 🤔 It should still be possible to partition any dictionary though, I mean not all words can be combined with every other word or the combinatorics would be insane, perhaps sacrificing some memory (duplicating words that combine with everything in all partitions) for better parallelization.

That sounds more complicated than I'd hoped though 😅

**Comment by wooorm** [comment]
It sounds pretty complicated indeed 😅

I’m closing this because the actual problem should in part be solved by the PR, making this issue less of a thing!
