### ISSUE TITLE
spell.correct with human names behavior.

### ISSUE THREAD

**Issue by s-a** [wooorm/nspell#4]
While `console.log(spell.correct('Stephan')); //=> true` and `console.log(spell.correct('stephan')); //=> false` there might be some name detection in `nspell`. Does there exists a way to configure `nspell` that `console.log(spell.correct('Stephan'));` yields `false`? I need a way to ignore names.

**Comment by wooorm** [comment]
Whether names are detected depends on the dictionary you’re using, and how it’s set up. Both [`en_GB`](https://github.com/wooorm/dictionaries/tree/master/dictionaries/en_GB) and [`en_US`](https://github.com/wooorm/dictionaries/tree/master/dictionaries/en_US) contain lots of properly cased names (`Stephan` too), and there’s no way to ignore some part of the dictionary.

You could create a [personal dictionary](https://github.com/wooorm/nspell#personal-dictionary-documents), and forbid a big list of names (`*Stephan\n*Stephanie\n...`), or, modify the [`.dic` file](https://github.com/wooorm/nspell#dictionary-documents) you pass in?

**Comment by s-a** [comment]
Unfortunately I try to detect names in a list of words, so it is not possible to declare a blacklist. But thanks for your detailed description.
