### ISSUE TITLE
Not loading big dictionary

### ISSUE THREAD

**Issue by aramis-it** [wooorm/nspell#49]
aff 0.5MB
dic 16MB

Is there any solution?
Is it possible to use database?

**Comment by wooorm** [comment]
Not enough information.

**Comment by aramis-it** [comment]
Can you tell me what information is needed?
OS: windows 11 
Browser: Edge latest 
RAM: 8GB

Aff lines: 15000
Dic lines: 574000

**Comment by aramis-it** [comment]
It stuck parsing the dic file at line 9629. 
https://github.com/bataak/dict-mn

**Comment by wooorm** [comment]
well, the readme suggest you use `dictionaries`. Not all dictionaries are UTF8 and hence can work with this project. If you use custom dictionaries, you need to turn them into UTF8 yourself. Can you use https://github.com/wooorm/dictionaries/tree/main/dictionaries/mn instead?

**Comment by aramis-it** [comment]
Yeh, I tried that result same.

**Comment by wooorm** [comment]
Same issue as GH-11. The Mongolian dictionary generates a bazillion words. `nspell` can’t handle a bazillion words.
