### ISSUE TITLE
Is stemming supported?

### ISSUE THREAD

**Issue by groe** [wooorm/nspell#6]
Hi!

Nspell looks very promising. I would like to use it for stemming with hunspell dictionaries (similar to [Solr's Hunspell Stemmer](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/hunspell/Stemmer.java)). Is that possible? If so, could you give me a hint in the right direction maybe?

Thanks!
Benjamin

**Comment by wooorm** [comment]
Hi Benjamin!

That’s probably possible, sure, but it looks like their own algorithm based on hunspell-compatible dictionaries. So I think you’re looking for a package like nspell, with very different code.

If you’re good at programming in Java and JavaScript the starting point would probably be to port their code over?

**Comment by groe** [comment]
Okay, thanks a lot, @wooorm!
