### ISSUE TITLE
Bug handling Russian

### ISSUE THREAD

**Issue by mikeb-celtx** [wooorm/nspell#7]
I tried NSpell out because of its richer API versus other Hunspell-compatible solutions, but I found that, for example, it did not recognize the Russian word очень, despite the word being in the dictionary file with no flags whatsoever.

Perhaps I'm missing something?

**Comment by wooorm** [comment]
I don’t know Russian, so it’s hard for me to test Russian. If it’s buggy, and it definitely could be, we need someone with familiarity of that language to come in and help writing tests and fixes!

**Comment by mikeb-celtx** [comment]
Sadly, I don't know Russian either, and we've had to move away from NSpell in the meantime. I do like your API, however, and maybe at some point I can revisit that decision. I expect, however, that for performance reasons we'll also be looking at a WebAssembly solution, so I can't guarantee anything.

**Comment by wooorm** [comment]
Uhm, it’s working for me 🤷‍♂️

```js
var dictionary = require('dictionary-ru')
var nspell = require('nspell')

dictionary(function(err, dict) {
  if (err) throw err
  var spell = nspell(dict)
  console.log(spell.spell('очень')) // => { correct: true, forbidden: false, warn: false }
})
```
