### ISSUE TITLE
Not playing well with 'dictionary-it'

### ISSUE THREAD

**Issue by brandon-pereira** [wooorm/nspell#9]
Hey!

Love the library, been really helpful in solving an issue we had. We have this repo successfully working with 'dictionary-en-gb', 'dictionary-fr', and 'dictionary-de'. However, we also need to use 'dictionary-it'. 

The Italian dictionary callback gets called (their repo loads the files into memory) but when I pass it into nspell It hangs and eventually crashes because it ran out of memory.

```javascript
const nspell = require("nspell");
const dict = require('dictionary-it');

dict((err, cb) => {
  // we get here, cb is an obj containing 'aff' and 'dic'.
  const data = nspell(cb);
  // we never get to the cb below, cpu and memory usage spike
  console.log(data);
})
```

I even tried upping the default memory allowance in node (via `--max_old_space_size=2048`)  but that just causes it to indefinitely hang. 

Note: if I load just the 'aff' file and not the 'dic' file it gets to the console.log, but the dic file seems to be causing issues.

Could this be because the Italian dictionary is simply too big? Although running on a 2.5 GHz Intel Core i7 with 16gb of ram it should load eventually.

I'd love some help debugging the problem if possible!

**Comment by brandon-pereira** [comment]
Wow, thanks the the insanely fast response! I've done just that, and have gotten in a little deeper. I'm not entirely sure whats going on so it makes this very difficult, but one thing I've noticed about Italian as opposed to German/French/English is that it makes it to line 91 of ./lib/util/dictionary much more frequently. In German, the "otherNewWords" variable is typically 3 items max, whereas in Italian I only processed about a 10th of the file and the "otherNewWords" (as shown below) was already very large. I believe this is whats causing the memory issues, as it's required to loop over every item in this array every time.

```javascript
line 91 called abbandonare 15 26
[ 'l\'abbandonacelo',
  'l\'Abbandonacelo',
  'L\'Abbandonacelo',
  'all\'abbandonacelo',
  'all\'Abbandonacelo',
  'All\'Abbandonacelo',
  'dell\'abbandonacelo',
  'dell\'Abbandonacelo',
  'Dell\'Abbandonacelo',
  'dall\'abbandonacelo',
  'dall\'Abbandonacelo',
  'Dall\'Abbandonacelo',
  'nell\'abbandonacelo',
  'nell\'Abbandonacelo',
  'Nell\'Abbandonacelo',
  'sull\'abbandonacelo',
  'sull\'Abbandonacelo',
  'Sull\'Abbandonacelo',
  'coll\'abbandonacelo',
  'coll\'Abbandonacelo',
  'Coll\'Abbandonacelo',
  'd\'abbandonacelo',
  'd\'Abbandonacelo',
  'D\'Abbandonacelo',
  'quest\'abbandonacelo',
  'quest\'Abbandonacelo',
  'Quest\'Abbandonacelo',
  'quell\'abbandonacelo',
  'quell\'Abbandonacelo',
  'Quell\'Abbandonacelo' ]
```

Again, very sorry I'm not entirely sure how this code is creating a dictionary. I'm still going to continue investigating on my end but was hoping you could help point me in the right direction.

**Comment by brandon-pereira** [comment]
I've gotten this much father. Commenting out some things caused the code work work. 

[See my commit here]( https://github.com/brandon-pereira/nspell/commit/015acc95395ad8d3bf43ab192fdc2116d0c0aee6)

I'm sure this code does something, although I'm not familiar with what it does.

I ran your unit tests and they all passed (see below)

```
1..91
# tests 91
# pass  91
```

This dictionary still takes a long time to load. Here's time timestamps for each language for me to load them (and do some additional dictionary appends). This is unit tests from my code, so results my vary.

```
 PASS  test/spellchecker.test.js (35.073s)
  ✓ SpellChecking English should work (295ms)
  ✓ SpellChecking French should work (3712ms)
  ✓ SpellChecking Italian should work (24802ms) <-- this took 24 seconds!!!
  ✓ SpellChecking German should work (3442ms)
```

If you'd like, I can cleanup the code (by removing the commented out lines) and merge it. However I'm a bit hesitant about deleting random things and calling it fixed.

Let me know how to continue.

Thanks!

**Comment by wooorm** [comment]
Sorry for the delayed response! Thanks for investigating it so well, @brandon-pereira!

- Maybe it’s slow because [this part doesn’t do anything](https://github.com/brandon-pereira/nspell/blob/015acc95395ad8d3bf43ab192fdc2116d0c0aee6/lib/util/add.js#L53-L78)?
- The combinable part here references to hunspell: `PFX flag cross_product number` or `SFX flag cross_product number`, where `man 5 hunspell` defines `cross_product` as: “Cross product (permission to combine prefixes and suffixes).  Possible values: Y (yes) or N (no)”. That’s checked for [here](https://github.com/wooorm/nspell/blob/874ab1a304c2da229ac9658a90d6510b212c4fcc/lib/util/affix.js#L180).
- The it dictionary seems to have a lot of PFX and SFX entries, with Y on, namely 489 and 2744, whereas nl has 44 and 452 respectively, and en-US has 14 and 59.

Do you know Italian and could you check if it still “works” without this loop?

**Comment by brandon-pereira** [comment]
Hey @wooorm I have an Italian translator here who can investigate this. Give me a day or two to work with them to figure this out.

**Comment by wooorm** [comment]
Oh that’s great, thanks Brandon!

**Comment by brandon-pereira** [comment]
I've talked with my translator, removing these lines works but we don't feel comfortable doing a pull request to master. I'll use my forked version as a dependency in my project (partial spellchecking is better than no spellchecking for us). Thanks for the help with this, sorry I wasn't able to help with a better fix!
